{
  "openapi": "3.0.0",
  "info": {
    "title": "API Desafio Sharenergy",
    "description": "Route documentation for Desafio Sharenergy API",
    "version": "1.0.0"
  },
  "basePath": "/",

  "paths": {
    "/customers": {
      "post": {
        "summary": "Create a customer",
        "tags": ["Customers"],
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateCustomer"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCustomer"
                },
                "examples": {
                  "createCustomer": {
                    "value": {
                      "id": "b287c19c-ff6e-4579-9218-277618f62c76",
                      "name": "_anycustumer",
                      "email": "_any@email.com",
                      "phoneNumber": "00000000000",
                      "cpf": "000.000.000-00",
                      "address": {
                        "id": "32c97d33-9640-427f-9201-d8c8082aec0e",
                        "street": "_anystreet, 000",
                        "district": "_anydistrict",
                        "zipcode": "00000000",
                        "city": "_anycity",
                        "state": "_anystate",
                        "customerId": "b287c19c-ff6e-4579-9218-277618f62c76"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "stateIsRequired": {
                    "value": [
                      {
                        "message": "\"state\" is required",
                        "path": ["state"],
                        "type": "any.required",
                        "context": {
                          "label": "state",
                          "key": "state"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      },
      "get": {
        "summary": "Find all customers",
        "tags": ["Customers"],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/ResponseCustomer"
                  }
                },
                "examples": {
                  "findAllCustomers": {
                    "value": [
                      {
                        "id": "b287c19c-ff6e-4579-9218-277618f62c76",
                        "name": "_anycustumer",
                        "email": "_any@email.com",
                        "phoneNumber": "00000000000",
                        "cpf": "000.000.000-00",
                        "address": {
                          "id": "32c97d33-9640-427f-9201-d8c8082aec0e",
                          "street": "_anystreet, 000",
                          "district": "_anydistrict",
                          "zipcode": "00000000",
                          "city": "_anycity",
                          "state": "_anystate",
                          "customerId": "b287c19c-ff6e-4579-9218-277618f62c76"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/customers/{id}": {
      "get": {
        "summary": "Find one customer",
        "tags": ["Customers"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Customer id to update",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCustomer"
                },
                "examples": {
                  "findOneCustomer": {
                    "value": {
                      "id": "b287c19c-ff6e-4579-9218-277618f62c76",
                      "name": "_anycustumer",
                      "email": "_any@email.com",
                      "phoneNumber": "00000000000",
                      "cpf": "000.000.000-00",
                      "address": {
                        "id": "32c97d33-9640-427f-9201-d8c8082aec0e",
                        "street": "_anystreet, 000",
                        "district": "_anydistrict",
                        "zipcode": "00000000",
                        "city": "_anycity",
                        "state": "_anystate",
                        "customerId": "b287c19c-ff6e-4579-9218-277618f62c76"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "examples": {
                  "customerNotFound": {
                    "value": {
                      "statusCode": 404,
                      "method": "findCustomerById",
                      "message": "Customer {6dfa8509-50fb-43db-8fbb-d923b64a0122d} not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update a customer",
        "tags": ["Customers"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Customer id to update",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseCustomer"
                },
                "examples": {
                  "updateCustomer": {
                    "value": {
                      "id": "b287c19c-ff6e-4579-9218-277618f62c76",
                      "name": "_anycustumer",
                      "email": "_any@email.com",
                      "phoneNumber": "00000000000",
                      "cpf": "000.000.000-00",
                      "address": {
                        "id": "32c97d33-9640-427f-9201-d8c8082aec0e",
                        "street": "_anystreet, 000",
                        "district": "_anydistrict",
                        "zipcode": "00000000",
                        "city": "_anycity",
                        "state": "_anystate",
                        "customerId": "b287c19c-ff6e-4579-9218-277618f62c76"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "stateIsRequired": {
                    "value": [
                      {
                        "message": "\"state\" is required",
                        "path": ["state"],
                        "type": "any.required",
                        "context": {
                          "label": "state",
                          "key": "state"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete a customer",
        "tags": ["Customers"],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "Customer id to delete",
            "required": true
          }
        ],
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "examples": {
                  "customerNotFound": {
                    "value": {
                      "statusCode": 404,
                      "method": "deleteCustomer",
                      "message": "Customer {022ad5cd-ae23-43cb-85a6-069438d64f4fd} not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "summary": "Create user",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUser"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseUser"
                },
                "examples": {
                  "createUser": {
                    "value": {
                      "id": "9fa2df1c-8c67-4bf7-8802-8e0ed47f3dca",
                      "email": "_any@email.com",
                      "password": "$2b$08$PxAkcnF/EvAbEszzefdDzOxRCUlk/1LrzTlrJZTM17U9r1pvo1wC6",
                      "createdAt": "2023-01-05T01:46:11.003Z"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "emailIsRequired": {
                    "value": [
                      {
                        "message": "\"email\" is required",
                        "path": ["email"],
                        "type": "any.required",
                        "context": {
                          "label": "email",
                          "key": "email"
                        }
                      }
                    ]
                  },
                  "passwordIsRequired": {
                    "value": [
                      {
                        "message": "\"password\" is required",
                        "path": ["password"],
                        "type": "any.required",
                        "context": {
                          "label": "password",
                          "key": "password"
                        }
                      }
                    ]
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/users/{id}": {
      "get": {
        "summary": "Find one user",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "User id to find",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseUser"
                },
                "examples": {
                  "findOneUser": {
                    "value": {
                      "id": "9fa2df1c-8c67-4bf7-8802-8e0ed47f3dca",
                      "username": "_anyusername",
                      "password": "$2b$08$PxAkcnF/EvAbEszzefdDzOxRCUlk/1LrzTlrJZTM17U9r1pvo1wC6",
                      "createdAt": "2023-01-05T01:46:11.003Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "examples": {
                  "customerNotFound": {
                    "value": {
                      "statusCode": 404,
                      "method": "findUserById",
                      "message": "User {9fa2df1c-8c67-4bf7-8802-8e0ed47f3dcad} not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete a user",
        "tags": ["Users"],
        "security": [{ "bearerAuth": [] }],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "User id to delete",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Ok"
          },
          "404": {
            "description": "Not found",
            "content": {
              "application/json": {
                "examples": {
                  "customerNotFound": {
                    "value": {
                      "statusCode": 404,
                      "method": "findUserById",
                      "message": "User {9fa2df1c-8c67-4bf7-8802-8e0ed47f3dcad} not found"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Unauthorized"
                },
                "examples": {
                  "tokenIsMissing": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token is missing"
                    }
                  },
                  "tokenInvalid": {
                    "value": {
                      "statusCode": 401,
                      "method": "authenticateUser",
                      "message": "Token invalid"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Login a user",
        "tags": ["Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUser"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResponseToken"
                },
                "examples": {
                  "loginUser": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkplXVCJ9.eyJpZCI6ImZlMjZiYWFhLTMwYzktNDRkYS05NjNhLWQyN2RiOTFkZjk0OCIsImVtYWlsIjoianZpbHZhbUBvb3NrZC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCQ3SE9CTDh4c05uUGpCZlFWLzRYeGwuTGM3NjMuVUxqNHlpOXRCcWpDTERhWnpocHE2S3ptZSIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDNUMDA6NDE6MzIuNjIwWiIsImlhdCI6MTY3Mjg4MzY4NSwiZXhwIjoxNjczMzE1Njg1LCJzdWIiOiJmZTI2YmFhYS0zMGM5LTQ0ZGEtOTYzYS1kMjdkYjkxZGY5NDgifQ.yFvgFvfuLxZL4W7N-AvgPeHKgdzmQFNuG4KgEKOUAbU",
                      "refreshToken": {
                        "id": "43b53993-a81e-4812-a623-ff5fb2e9ccaa",
                        "expiresIn": 1673315685,
                        "userId": "fe26baaa-30c9-44da-963a-d27db91df948"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "emailOrPasswordIncorrect": {
                    "value": {
                      "statusCode": 400,
                      "method": "authenticateUser",
                      "message": "Incorrect username or password"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/refresh-token": {
      "post": {
        "summary": "Refresh token",
        "tags": ["Auth"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "refreshToken": { "type": "string" }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": { "type": "string" }
                  }
                },
                "examples": {
                  "refreshToken": {
                    "value": {
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZlMjZiYWFhLTMwYzktNDRkYS05NjNhLWQyN2RiOTFkZjk0OCIsImVtYWlsIjoianZpbHZhbUBvb3NrZC5jb20iLCJwYXNzd29yZCI6IiQyYiQwOCQ3SE9CTDh4c05uUGpCZlFWLzRYeGwuTGM3NjMuVUxqNHlpOXkRCcWpDTERhWnpocHE2S3ptZSIsImNyZWF0ZWRBdCI6IjIwMjMtMDEtMDNUMDA6NDE6MzIuNjIwWiIsImlhdCI6MTY3Mjg4Mzg5MSwiZXhwIjoxNjczMzE1ODkxLCJzdWIiOiJmZTI2YmFhYS0zMGM5LTQ0ZGEtOTYzYS1kMjdkYjkxZGY5NDgifQ.0aw0B3IkG8az32Y176vUiGhcL6xv6UcVINeD6fkgynM"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "examples": {
                  "invalidRefreshToken": {
                    "value": {
                      "statusCode": 400,
                      "method": "refreshToken",
                      "message": "Invalid refresh token"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "CreateCustomer": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" },
          "phoneNumber": { "type": "string" },
          "cpf": { "type": "string" },
          "street": { "type": "string" },
          "district": { "type": "string" },
          "zipcode": { "type": "string" },
          "city": { "type": "string" },
          "state": { "type": "string" }
        }
      },
      "ResponseCustomer": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "name": { "type": "string" },
          "email": { "type": "string" },
          "phoneNumber": { "type": "string" },
          "cpf": { "type": "string" },
          "address": {
            "type": "object",
            "properties": {
              "id": { "type": "string" },
              "street": { "type": "string" },
              "district": { "type": "string" },
              "zipcode": { "type": "string" },
              "city": { "type": "string" },
              "state": { "type": "string" },
              "customerId": { "type": "string" }
            }
          }
        }
      },
      "UpdateCustomer": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "email": { "type": "string" },
          "phoneNumber": { "type": "string" },
          "cpf": { "type": "string" },
          "address": {
            "type": "object",
            "properties": {
              "street": { "type": "string" },
              "district": { "type": "string" },
              "zipcode": { "type": "string" },
              "city": { "type": "string" },
              "state": { "type": "string" },
              "customerId": { "type": "string" }
            }
          }
        }
      },
      "CreateUser": {
        "type": "object",
        "properties": {
          "username": { "type": "string" },
          "password": { "type": "string" }
        }
      },
      "ResponseUser": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "username": { "type": "string" },
          "password": { "type": "string" },
          "createdAt": { "type": "string" }
        }
      },
      "ResponseToken": {
        "type": "object",
        "properties": {
          "token": { "type": "string" },
          "refreshToken": {
            "type": "object",
            "properties": {
              "id": { "type": "string" },
              "expiresIn": { "type": "string" },
              "userId": { "type": "string" }
            }
          }
        }
      },
      "Unauthorized": {
        "type": "object",
        "properties": {
          "statusCode": { "type": "number" },
          "method": { "type": "string" },
          "message": { "type": "string" }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
